### ISSUE TITLE
Crash when Internet Connection is reconnected

### ISSUE THREAD

**Issue by korbinio** [bwp91/homebridge-deebot#53]
### What issue do you have? Please be as thorough and explicit as possible.
Everytime my internet connection is shortly interrupted homebridge throws the following error:
```
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)
```
After searching a lot I could pinpoint the issue to the homebridge-deebot plugin. When I disable the plugin and the trigger a reconnect in my router nothing happens. As soon as the plugin is enabled the error is thrown and homebridge is shut down.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge
* Which version of Homebridge/HOOBS do you have?
 v1.4.0
* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Rasperry Pi with Homebridge OS, Node.js v16.13.2
* Which version of this plugin (homebridge-deebot) do you have? Has the issue started since upgrading from a previous version?
latest version v4.4.1 (just started using this plugin, so no update history)
* Which ECOVACS devices do you have that are causing issues? Please include product models if applicable.
I dont think it is relevant, but my Ecovas Device is a Deebot Ozmo 950

**Comment by mrbungle64** [comment]
@korbinio @bwp91 

I can confirm that this error currently occurs for components that use the ecovacs-deebot.js library.

But I still don't know if it is triggered by the library itself or by the implementions that are using the library, because I'm able to reproduce it with the Node-RED integration and also the ioBroker adapter. But I cannot reproduce it with the library itself.
The error occours `at TLSWrap.onStreamRead (node:internal/stream_base_commons:2xx:20)` (not in the library) and there are also several other reports of different integrations with the same problem.

I already made some changes to the library with version 0.7.2-alpha.6 which is already used by the beta version of the homebridge-deebot plugin. Maybe you can try if the same error occours with the version 4.4.2-beta.1 in your case.

**Comment by korbinio** [comment]
@mrbungle64 I updated to the beta version (v4.4.2-beta.1):
When I interupt the internet connection in my router homebridge is still being restarted, but the error is now not specified anymore:
```
[07/02/2022, 14:27:48] [Deebot] [DEEBOT OZMO 950 Series] has been reported [offline].
[07/02/2022, 14:27:51] Got SIGTERM, shutting down Homebridge...
```
So the error message is not displayed anymore, but the problem persists... (During my testing the reboot was not always triggered right after the reconnect but took sometimes a minute or two to cause the reboot)

**Comment by mrbungle64** [comment]
@korbinio 

In the meantime I already released version 0.7.2-alpha.8
I don't know if it's already used in your installation.

**Comment by korbinio** [comment]
I think we have to wait for @bwp91 to weight in on this one. From the changelog of v4.4.2-beta.1 I can only take that it uses "v0.7.2 (prerelease)" of ecovacs-deebot, but not specifically which version...

**Comment by mrbungle64** [comment]
@korbinio 

I just released 0.7.2-alpha.9
Please reinstall the plugin. It should use this version then.
It was obviously caused by [a bug](https://github.com/mqttjs/MQTT.js/pull/1401) in the [mqtt client](https://github.com/mqttjs/MQTT.js) version 4.3.4.
The new version of the library now uses version 4.3.5.

**Comment by korbinio** [comment]
This seems to have solved the problem! After a reconnect the log looks like this:
```
[07/02/2022, 20:36:06] [Deebot] [DEEBOT OZMO 950 Series] sent error [Connection is interrupted: MQTT client error: read ECONNRESET].
[07/02/2022, 20:36:06] [Deebot] [DEEBOT OZMO 950 Series] sent error [Received error event: MQTT server is offline or not reachable].
```

No reboot of homebridge was triggered. Thank you for the quick fix!

**Comment by bwp91** [comment]
Thanks for sorting this out @mrbungle64 

@korbinio does the device reconnect properly when the internet comes back online again?

**Comment by korbinio** [comment]
Yes, the reconnect works perfect. There is no output in the log, but the device is instantly controllable after the reconnect.
