### ISSUE TITLE
Support custom areas (in addition to spot areas)

### ISSUE THREAD

**Issue by apfelnutzer** [bwp91/homebridge-deebot#83]
* **Please explain your feature request in a one or two sentences.**
Currently the plug-in only supports spot areas defined upfront in the (Yeedi) app. Those are mapped to so called custom areas in the plug-in. I'd like to be able to also map actual custom areas (defined by coordinates) as custom areas in the plug-in.

* **Is your feature request related to a problem? Please describe.**
We have a combined living and dining room, which I'd like to be able to clean separately. Unfortunately the room was recognized as one room during the map creation (no matter what I tried) and at least the Yeedi app does not offer a feature to edit the map afterwards. Thus I need to work with custom areas (in the Yeedi app) defined by coordinates to do so.

* **Any particular ECOVACS devices that this relates to?**
I'm using a Yeedi Mop Station.

* **Anything else?**
I suggest to integrate the new feature in the device specific configuration along with the support of spot areas. One could provide the coordinates (in my case e.g. for the living room) instead of a spot area ID. The plug-in would need to distinguish these cases and trigger either a spot area or custom area cleaning. See [link](https://github.com/mrbungle64/ecovacs-deebot.js/wiki/CustomArea) for details re: triggering a custom area cleaning using the library at hand.

**Comment by apfelnutzer** [comment]
@bwp91, what do you think about this?

**Comment by bwp91** [comment]
I’m not against the idea but let me explain.
There exists another deebot plugin that came before mine which offers much more functionality like this, including i believe custom coordinates.
I originally made this plugin to be the “simple” version since my deebot device has basically on/off and 2 speeds, i just wanted something simple to control my device with.
Over time there have been little feature enhancements i have done only because users have mentioned that the other plugin wasn’t working for them. I’ve never wanted to “take over” the great functionality of the other plugin.
That said, I’m not sure if the current state of the other plugin whether it is still maintained and still works, maybe @mrbungle64 has anything to say about the other plugin, maybe not.

I’ve always wanted to opt for simplicity of plugins ie not having loads of random switches displaying in the home app which can make the ui look ugly. This is why I implemented the room cleaning like I did via the Eve app so that only “wanted” scenes would appear in the home app.

I guess I would be happy to implement something for custom coordinates, I just need to have a think about the best way I would want to have it shown in the Home/Eve app.

Of course if you have any ideas then please do share!

**Comment by apfelnutzer** [comment]
Well the way I suggested to implement it would be similar to the room cleaning. In fact from a UI/UX perspective it would be the same. This would "fix" the inability of the Yeedi software to recognize different rooms that are actually one big room, but used as two (or more) rooms. Maybe that helps!

**Comment by mrbungle64** [comment]
@bwp91 

> That said, I’m not sure if the current state of the other plugin whether it is still maintained and still works, maybe @mrbungle64 has anything to say about the other plugin, maybe not.

I don't have any more information about it, but it's fair to assume that the other plugin is no longer adequately maintained.
But it would be better if you asked him directly 😉 

Btw: I have the impression that your plugin has already been the preferred plugin for users for quite some time.

**Comment by apfelnutzer** [comment]
@bwp91, I could give it a try on my own (via PR), if you don't mind?

**Comment by bwp91** [comment]
Hi @apfelnutzer 
Sorry I have had so little free time recently i haven’t had a chance to even think about this or the 100 other issues combined on my other plugins 😅
Please feel free to work on a PR if you feel up to it, are you happy getting the plugin installed locally and “linked” to homebridge?

**Comment by apfelnutzer** [comment]
Haven't considered that yet, but I will try to set it all up locally (next weekend?)!

**Comment by apfelnutzer** [comment]
... everything is set up now - I will look into this starting this evening :-).

**Comment by apfelnutzer** [comment]
@bwp91, I just noticed, that the current spot area support is called "custom areas" throughout the code. I'm about to add custom area support now, so we should probably clean that up to avoid misunderstandings... Any suggestions I could consider right away, or do you prefer to do this during a review of my changes? I could also make a suggestion?

**Comment by apfelnutzer** [comment]
... what about "Predefined Areas" instead of "Custom Areas" as a more generic term for spot areas and custom areas (as defined in the library and API)?

**Comment by bwp91** [comment]
I don’t mind how it’s named so long as its understandable, does it have terminology in the ecovacs app?

**Comment by apfelnutzer** [comment]
I don't use the Ecovacs app as I own a Yeedi robot, but I suppose there's no need for a generic term to summarize both type of areas. I decided for "Predefined areas" so far (see PR).
